SELECT AREA_NAME 지역명, MEMBER_ID 아이디, MEMBER_NAME 이름, GRADE_NAME 등급명
FROM TB_MEMBER
JOIN TB_GRADE ON(GRADE = GRADE_CODE)
JOIN TB_AREA ON (AREA_CODE = AREA_CODE)
WHERE AREA_CODE = (
    SELECT AREA_CODE FROM TB_MEMBER
    WHERE 이름 = '김영희')
ORDER BY 이름 DESC;

​


SELECT A.AREA_NAME 지역명, M.MEMBER_ID 아이디, M.MEMBER_NAME 이름, G.GRADE_NAME 등급명
FROM TB_MEMBER
JOIN TB_GRADE ON(M.GRADE = G.GRADE_CODE)
JOIN TB_AREA ON (A.AREA_CODE = M.AREA_CODE)
WHERE AREA_CODE = (
        SELECT AREA_CODE 
        FROM TB_MEMBER
        WHERE MEMBER_NAME = '김영희' )
ORDER BY MEMBER_NAME ASC;

