CREATE USER sample02 IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO sample02;

CREATE TABLE TB_USER(
USER_ID VARCHAR2(20) PRIMARY KEY,
USER_PWD VARCHAR2 NOT NULL,
USER_NAME VARCHAR2(30),
USER_AGE NUMBER,
USER_EMAIL VARCHAR2(50),
CONSTRAINT USER_EMAIL_UNQ UNIQUE(USER_EMAIL)
);

CREATE TABLE TB_BOARD(
BOARD_NO NUMBER PRIMARY KEY,
BOARD_TITLE VARCHAT2(100),
BOARD_CONTENT VARCHAR2(4000),
BOARD_WRITER VARCHAR2(20) REFERENCES TB_USER(USER_ID) ON DELETE CASCADE,
BOARD_REG_DATE DATE DEFAULT SYSDATE
);